<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>NxEskd.Configurator</AssemblyName>
    <RootNamespace>NxEskd.Configurator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NxEskd.Core\NxEskd.Core.csproj" />
    <ProjectReference Include="..\..\..\NXKeys.Protocol\NXKeys.Protocol.csproj" />
  </ItemGroup>
</Project>
