using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NX2512_HotkeyStudio.Models;

namespace NX2512_HotkeyStudio.Services
{
    public static class OverlayGenerator
    {
        public static string GenerateOverlay(
            int version,
            string menubarID,
            List<ResolutionResult> resolutions,
            Dictionary<string, List<ConflictItem>> conflicts,
            bool clearConflicts,
            IEnumerable<ModuleConfig> modules = null,
            string daemonCmdPath = "",
            string guiCmdPath = "")
        {
            int menVersion = MenuScriptDefaults.NormalizeVersion(version);
            if (string.IsNullOrWhiteSpace(menubarID)) menubarID = "UG_GATEWAY_MAIN_MENUBAR";

            string daemonCmd = string.IsNullOrWhiteSpace(daemonCmdPath) ? "launch-hotkeystudio-daemon.cmd" : daemonCmdPath;
            string guiCmd = string.IsNullOrWhiteSpace(guiCmdPath) ? "launch-hotkeystudio-gui.cmd" : guiCmdPath;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("! Generated by NXKeys Studio. Do not edit manually.");
            sb.AppendLine("! Safe MenuScript overlay: no Siemens installation files are replaced.");
            sb.AppendLine($"VERSION {menVersion}");
            sb.AppendLine($"EDIT {menubarID}");
            sb.AppendLine();
            sb.AppendLine("AFTER UG_TOOLBOX");
            sb.AppendLine("    CASCADE_BUTTON UG_NXKEYS_CASCADE");
            sb.AppendLine("    LABEL NXKeys Studio");
            sb.AppendLine("END_OF_AFTER");
            sb.AppendLine();
            sb.AppendLine("MENU UG_NXKEYS_CASCADE");
            AppendBridgeButton(sb);
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_START_DAEMON");
            sb.AppendLine("    LABEL Включить Leader Key");
            sb.AppendLine($"    ACTIONS SYSTEM \"{daemonCmd}\"");
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_OPEN_STUDIO");
            sb.AppendLine("    LABEL Настройки NXKeys Studio...");
            sb.AppendLine($"    ACTIONS SYSTEM \"{guiCmd}\"");
            AppendSelectionFilterCascadeButton(sb, modules);
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
            sb.AppendLine("MENU UG_TOOLBOX");
            sb.AppendLine("    SEPARATOR");
            AppendBridgeButton(sb);
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_START_DAEMON");
            sb.AppendLine("    LABEL Включить Leader Key");
            sb.AppendLine($"    ACTIONS SYSTEM \"{daemonCmd}\"");
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_OPEN_STUDIO");
            sb.AppendLine("    LABEL Настройки NXKeys Studio...");
            sb.AppendLine($"    ACTIONS SYSTEM \"{guiCmd}\"");
            AppendSelectionFilterCascadeButton(sb, modules);
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
            AppendSelectionFilterMenu(sb, modules);

            sb.AppendLine("MENU UG_APPLICATION");
            AppendBridgeButton(sb);
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
            sb.AppendLine("MODIFY");

            HashSet<string> cleared = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            if (clearConflicts && conflicts != null)
            {
                foreach (ResolutionResult res in resolutions)
                {
                    if (res.Status != ResolutionStatus.Resolved || res.Binding == null || !res.Binding.Enabled) continue;

                    if (conflicts.TryGetValue(res.Binding.Shortcut, out List<ConflictItem> conflictList))
                    {
                        foreach (ConflictItem c in conflictList)
                        {
                            if (c.Command == null || string.IsNullOrWhiteSpace(c.Command.ID)) continue;
                            string key = c.Command.ID.Trim();
                            if (key.StartsWith("UG_VIEW_POPUP_", StringComparison.OrdinalIgnoreCase)) continue;
                            if (cleared.Add(key))
                            {
                                sb.AppendLine($"\n    ! Clear detected conflict: {SanitizeComment(c.Command.DisplayLabel)}");
                                sb.AppendLine($"    BUTTON {key}");
                                sb.AppendLine("    ACCELERATOR");
                            }
                        }
                    }
                }
            }

            if (resolutions != null)
            {
                foreach (ResolutionResult res in resolutions)
                {
                    if (res.Status != ResolutionStatus.Resolved || res.Binding == null || !res.Binding.Enabled) continue;
                    if (res.CommandID.StartsWith("UG_VIEW_POPUP_", StringComparison.OrdinalIgnoreCase)) continue;

                    sb.AppendLine($"\n    ! {SanitizeComment(res.Binding.Command?.Name)} [{SanitizeComment(res.Binding.Scope)}]");
                    sb.AppendLine($"    BUTTON {res.CommandID}");
                    sb.AppendLine($"    ACCELERATOR {res.Binding.Shortcut}");
                }
            }

            sb.AppendLine("\nEND_OF_MODIFY");
            return sb.ToString();
        }

        private static void AppendBridgeButton(StringBuilder sb)
        {
            sb.AppendLine("    BUTTON UG_NXKEYS_START_BRIDGE");
            sb.AppendLine("    LABEL Start NXKeys Bridge");
            sb.AppendLine("    TOOLBAR_LABEL NXKeys Bridge");
            sb.AppendLine("    MESSAGE Starts NXKeys Command Bridge.");
            sb.AppendLine("    BITMAP finished_flag");
            sb.AppendLine("    ACTIONS NX2512_CommandBridge.dll");
        }

        private static void AppendSelectionFilterCascadeButton(StringBuilder sb, IEnumerable<ModuleConfig> modules)
        {
            if (!SelectionFilterCommands(modules).Any()) return;
            sb.AppendLine();
            sb.AppendLine("    CASCADE_BUTTON UG_NXKEYS_SELECTION_FILTERS");
            sb.AppendLine("    LABEL Фильтры выбора геометрии");
        }

        private static void AppendSelectionFilterMenu(StringBuilder sb, IEnumerable<ModuleConfig> modules)
        {
            List<ModuleCommand> filters = SelectionFilterCommands(modules).ToList();
            if (filters.Count == 0) return;

            sb.AppendLine("MENU UG_NXKEYS_SELECTION_FILTERS");
            foreach (ModuleCommand filter in filters)
            {
                string buttonId = filter.Command?.ID?.Trim();
                if (string.IsNullOrWhiteSpace(buttonId)) continue;
                sb.AppendLine();
                sb.AppendLine("    BUTTON " + buttonId);
                if (!string.IsNullOrWhiteSpace(filter.Command?.Name))
                    sb.AppendLine("    LABEL " + SanitizeLabel(filter.Command.Name));
            }
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
        }

        private static IEnumerable<ModuleCommand> SelectionFilterCommands(IEnumerable<ModuleConfig> modules)
        {
            return (modules ?? Enumerable.Empty<ModuleConfig>())
                .Where(module => module != null &&
                                 module.Enabled &&
                                 string.Equals(module.ID, "selection_object", StringComparison.OrdinalIgnoreCase))
                .SelectMany(module => module.CommandSets ?? Enumerable.Empty<ModuleCommandSet>())
                .Where(set => set?.Commands != null)
                .SelectMany(set => set.Commands)
                .Where(command => command?.Command != null && !string.IsNullOrWhiteSpace(command.Command.ID));
        }

        private static string SanitizeComment(string val)
        {
            if (string.IsNullOrWhiteSpace(val)) return string.Empty;
            return val.Replace("\r", " ").Replace("\n", " ").Trim();
        }

        private static string SanitizeLabel(string val) => SanitizeComment(val).Replace("\"", "'");
    }
}
