using System;
using System.Collections.Generic;
using System.Text;
using NX2512_HotkeyStudio.Models;

namespace NX2512_HotkeyStudio.Services
{
    public static class OverlayGenerator
    {
        public static string GenerateOverlay(
            int version,
            string menubarID,
            List<ResolutionResult> resolutions,
            Dictionary<string, List<ConflictItem>> conflicts,
            bool clearConflicts,
            string daemonCmdPath = "",
            string guiCmdPath = "")
        {
            int menVersion = MenuScriptDefaults.NormalizeVersion(version);
            if (string.IsNullOrWhiteSpace(menubarID)) menubarID = "UG_GATEWAY_MAIN_MENUBAR";

            string daemonCmd = string.IsNullOrWhiteSpace(daemonCmdPath) ? "launch-hotkeystudio-daemon.cmd" : daemonCmdPath;
            string guiCmd = string.IsNullOrWhiteSpace(guiCmdPath) ? "launch-hotkeystudio-gui.cmd" : guiCmdPath;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("! Generated by NXKeys Studio. Do not edit manually.");
            sb.AppendLine("! Safe MenuScript overlay: no Siemens installation files are replaced.");
            sb.AppendLine($"VERSION {menVersion}");
            sb.AppendLine($"EDIT {menubarID}");
            sb.AppendLine();
            sb.AppendLine("AFTER UG_TOOLBOX");
            sb.AppendLine("    CASCADE_BUTTON UG_NXKEYS_CASCADE");
            sb.AppendLine("    LABEL NXKeys Studio");
            sb.AppendLine("END_OF_AFTER");
            sb.AppendLine();
            sb.AppendLine("MENU UG_NXKEYS_CASCADE");
            sb.AppendLine("    APPLICATION_BUTTON NXKEYS_COMMAND_BRIDGE");
            sb.AppendLine("    LABEL NXKeys Direct Command Bridge");
            sb.AppendLine("    LIBRARIES NX2512_CommandBridge");
            sb.AppendLine("    MENU_FILES nxkeys_command_bridge.men");
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_START_DAEMON");
            sb.AppendLine("    LABEL ⚡ Включить Leader Key");
            sb.AppendLine($"    ACTIONS SYSTEM \"{daemonCmd}\"");
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_OPEN_STUDIO");
            sb.AppendLine("    LABEL ⚙️ Настройки NXKeys Studio...");
            sb.AppendLine($"    ACTIONS SYSTEM \"{guiCmd}\"");
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
            sb.AppendLine("MENU UG_TOOLBOX");
            sb.AppendLine("    SEPARATOR");
            sb.AppendLine("    APPLICATION_BUTTON NXKEYS_COMMAND_BRIDGE");
            sb.AppendLine("    LABEL NXKeys Direct Command Bridge");
            sb.AppendLine("    LIBRARIES NX2512_CommandBridge");
            sb.AppendLine("    MENU_FILES nxkeys_command_bridge.men");
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_START_DAEMON");
            sb.AppendLine("    LABEL ⚡ Включить Leader Key");
            sb.AppendLine($"    ACTIONS SYSTEM \"{daemonCmd}\"");
            sb.AppendLine();
            sb.AppendLine("    BUTTON UG_NXKEYS_OPEN_STUDIO");
            sb.AppendLine("    LABEL ⚙️ Настройки NXKeys Studio...");
            sb.AppendLine($"    ACTIONS SYSTEM \"{guiCmd}\"");
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
            sb.AppendLine("MENU UG_APPLICATION");
            sb.AppendLine("    APPLICATION_BUTTON NXKEYS_COMMAND_BRIDGE");
            sb.AppendLine("    LABEL NXKeys Direct Command Bridge");
            sb.AppendLine("    LIBRARIES NX2512_CommandBridge");
            sb.AppendLine("    MENU_FILES nxkeys_command_bridge.men");
            sb.AppendLine("END_OF_MENU");
            sb.AppendLine();
            sb.AppendLine("MODIFY");

            HashSet<string> cleared = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            if (clearConflicts && conflicts != null)
            {
                foreach (ResolutionResult res in resolutions)
                {
                    if (res.Status != ResolutionStatus.Resolved || res.Binding == null || !res.Binding.Enabled) continue;

                    if (conflicts.TryGetValue(res.Binding.Shortcut, out List<ConflictItem> conflictList))
                    {
                        foreach (ConflictItem c in conflictList)
                        {
                            if (c.Command == null || string.IsNullOrWhiteSpace(c.Command.ID)) continue;
                            string key = c.Command.ID.Trim();
                            if (key.StartsWith("UG_VIEW_POPUP_", StringComparison.OrdinalIgnoreCase)) continue;
                            if (cleared.Add(key))
                            {
                                sb.AppendLine($"\n    ! Clear detected conflict: {SanitizeComment(c.Command.DisplayLabel)}");
                                sb.AppendLine($"    BUTTON {key}");
                                sb.AppendLine("    ACCELERATOR");
                            }
                        }
                    }
                }
            }

            if (resolutions != null)
            {
                foreach (ResolutionResult res in resolutions)
                {
                    if (res.Status != ResolutionStatus.Resolved || res.Binding == null || !res.Binding.Enabled) continue;
                    if (res.CommandID.StartsWith("UG_VIEW_POPUP_", StringComparison.OrdinalIgnoreCase)) continue;

                    sb.AppendLine($"\n    ! {SanitizeComment(res.Binding.Command?.Name)} [{SanitizeComment(res.Binding.Scope)}]");
                    sb.AppendLine($"    BUTTON {res.CommandID}");
                    sb.AppendLine($"    ACCELERATOR {res.Binding.Shortcut}");
                }
            }

            sb.AppendLine("\nEND_OF_MODIFY");
            return sb.ToString();
        }

        private static string SanitizeComment(string val)
        {
            if (string.IsNullOrWhiteSpace(val)) return string.Empty;
            return val.Replace("\r", " ").Replace("\n", " ").Trim();
        }
    }
}
