<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <AssemblyName>NXKeys.Protocol</AssemblyName>
    <RootNamespace>NXKeys.Protocol</RootNamespace>
  </PropertyGroup>
</Project>
