<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NX2512_HotkeyStudio\NX2512_HotkeyStudio.csproj" />
    <ProjectReference Include="..\NXKeys.BridgeCore\NXKeys.BridgeCore.csproj" />
  </ItemGroup>
</Project>
